const theme = {
  colors: {
    backgroundLight: "#fff",
    backgroundDark: "#3C4C55",
    headerLight: "#000",
    headerDark: "#fff",
    textLight: "#000",
    textDark: "#fff",
    selectionLight: "#B2AEFF",
    selectionDark: "#FFAEFF",
    lightGrey: "#EAEAEA",
    grey: "#f7f7f7",
    novaAqua: "#7FC1CA",
    novaBlue: "#83AFE5",
    novaPurple: "#9A93E1",
    novaPink: "#D18EC2",
    novaOrange: "#F2C38F",
    novaYellow: "#DADA93",
    novaGreen: "#A8CE93",
    novaGrey: "#899BA6",
    background: "#fff",
    text: "rgba(0, 0, 0, 0.84)",
    accent: "#b2aeff",
    primary: "#fff",
    secondary: "#191a1d",
    secondaryDark: "#101114",
    accent2: "#7b68ee",
    font: "#5e5e5e",
  },
  layout: {
    gutter: "3rem",
    smallBreakpoint: "500px",
    mediumBreakpoint: "750px",
    largeBreakpoint: "1000px",
    maxWidth: "75rem",
  },
  font: {
    thin: 300,
    regular: 400,
    medium: 500,
    bold: 700,
    extraBold: 800,
    black: 900,
  },
}

export default theme
